# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ".git"
default_stages:
  - commit
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.2
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [wandb, types-PyYAML, types-requests]
